spring:
  profiles.active: dev
  logging.level.ROOT: ERROR

  liquibase.change-log: classpath:liquibase/db.changelog-master.xml
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
---
spring:
  profiles: dev

  logging.level.ROOT: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:3030/testovoe
    username: testo
    password: Qwerty123

  jpa:
    show-sql: true
#    hibernate.ddl-auto: update

---
spring:
  profiles: embedded

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console



